# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60ed49cb744dd8a5ad71e616be4558540ec6075ccc141c4097694191015063bbc921886c3811f75652e49ce38cc7e12f5e56d004c01a24754473070add858bc5

test:
  secret_key_base: c91c818896ccf2820d06a2990bcdb9717941965395c3c2bcbc7a0fde8b5613420cb74402839f9e8ab78cf89ab2a69e0578c96b390b1e995c012dbb32ed5d8f1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
